version: '3.8'

services:
  virgo:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    entrypoint: ["/bin/sh"]
    command: ["-c", "/app/virgo migrate && /app/virgo server"]
    image: virgo
    ports:
      - "7000:7000"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: virgo
      POSTGRES_PASSWORD: virgo
      POSTGRES_DB: virgo
    volumes:
      - virgo_db:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - "8080:8080"  # Exposes Adminer on port 8080 of the host
    restart: unless-stopped

  # virgo-frontend:
  #   build:
  #     context: ../virgo-frontend
  #     dockerfile: ../virgo-frontend/Dockerfile
  #   ports:
  #     - "3000:80"
  #   environment:
  #     REACT_APP_SERVER_URL: "http://127.0.0.1:7000"
  #     REACT_APP_WEBSOCKET_SERVER_URL: "ws://127.0.0.1:7000/v1/ws"
  #   depends_on:
  #     - virgo

volumes:
  virgo_db:
